from __future__ import annotations

import json
import secrets
from collections.abc import AsyncIterator, Sequence
from contextlib import asynccontextmanager
from datetime import UTC, datetime, timedelta
from typing import Any

from psycopg.rows import dict_row
from psycopg_pool import AsyncConnectionPool


def utc_now() -> datetime:
    return datetime.now(UTC)


def to_iso(dt: datetime | None) -> str | None:
    if dt is None:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return dt.astimezone(UTC).isoformat()


def from_iso(value: str | None) -> datetime | None:
    if not value:
        return None
    return datetime.fromisoformat(value)


class Database:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url
        self.pool: AsyncConnectionPool | None = None

    @staticmethod
    def _sql(query: str) -> str:
        return query.replace("?", "%s")

    @asynccontextmanager
    async def _connection(self) -> AsyncIterator[Any]:
        if self.pool is None:
            raise RuntimeError("Database pool is not initialized.")
        async with self.pool.connection() as conn:
            yield conn

    async def connect(self) -> None:
        self.pool = AsyncConnectionPool(
            conninfo=self.database_url,
            min_size=1,
            max_size=10,
            open=False,
            kwargs={"row_factory": dict_row},
        )
        await self.pool.open(wait=True)
        async with self._connection() as conn:
            await self._create_schema(conn)
            await conn.commit()

    async def close(self) -> None:
        if self.pool is not None:
            await self.pool.close()
            self.pool = None

    async def _execute(self, query: str, params: Sequence[Any] = (), *, conn: Any) -> Any:
        return await conn.execute(self._sql(query), params)

    async def _fetchone(
        self,
        query: str,
        params: Sequence[Any] = (),
        *,
        conn: Any | None = None,
    ) -> dict[str, Any] | None:
        if conn is None:
            async with self._connection() as local_conn:
                return await self._fetchone(query, params, conn=local_conn)
        cursor = await self._execute(query, params, conn=conn)
        row = await cursor.fetchone()
        await cursor.close()
        return row

    async def _fetchall(
        self,
        query: str,
        params: Sequence[Any] = (),
        *,
        conn: Any | None = None,
    ) -> list[dict[str, Any]]:
        if conn is None:
            async with self._connection() as local_conn:
                return await self._fetchall(query, params, conn=local_conn)
        cursor = await self._execute(query, params, conn=conn)
        rows = await cursor.fetchall()
        await cursor.close()
        return list(rows)

    async def _create_schema(self, conn: Any) -> None:
        statements = (
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                telegram_id BIGINT NOT NULL UNIQUE,
                username TEXT,
                first_name TEXT,
                last_name TEXT,
                ref_code TEXT NOT NULL UNIQUE,
                referred_by BIGINT REFERENCES users(id),
                joined_at TEXT NOT NULL,
                last_seen_at TEXT NOT NULL,
                is_channel_member INTEGER NOT NULL DEFAULT 0,
                bonus_days_balance INTEGER NOT NULL DEFAULT 0,
                pending_discount_percent INTEGER NOT NULL DEFAULT 0,
                total_bonus_days_earned INTEGER NOT NULL DEFAULT 0,
                remnawave_uuid TEXT,
                remnawave_short_uuid TEXT,
                remnawave_subscription_url TEXT,
                subscription_expires_at TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id),
                plan_key TEXT NOT NULL,
                plan_name TEXT NOT NULL,
                days INTEGER NOT NULL,
                base_amount NUMERIC(12, 2) NOT NULL,
                final_amount NUMERIC(12, 2) NOT NULL,
                currency_type TEXT NOT NULL,
                fiat TEXT,
                asset TEXT,
                accepted_assets TEXT,
                promo_code TEXT,
                discount_percent INTEGER NOT NULL DEFAULT 0,
                payment_provider TEXT NOT NULL DEFAULT 'crypto_bot',
                payment_invoice_id TEXT,
                payment_label TEXT,
                payment_url TEXT,
                payment_extra_url TEXT,
                payment_status TEXT,
                crypto_invoice_id BIGINT,
                crypto_invoice_hash TEXT,
                crypto_bot_invoice_url TEXT,
                crypto_mini_app_invoice_url TEXT,
                crypto_web_app_invoice_url TEXT,
                crypto_invoice_status TEXT,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL,
                paid_at TEXT,
                activated_at TEXT,
                raw_invoice_json TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS promo_codes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code TEXT NOT NULL UNIQUE,
                bonus_days INTEGER NOT NULL DEFAULT 0,
                discount_percent INTEGER NOT NULL DEFAULT 0,
                max_uses INTEGER NOT NULL DEFAULT 0,
                uses_count INTEGER NOT NULL DEFAULT 0,
                is_active INTEGER NOT NULL DEFAULT 1,
                expires_at TEXT,
                description TEXT,
                created_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS promo_redemptions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                promo_id BIGINT NOT NULL REFERENCES promo_codes(id),
                user_id BIGINT NOT NULL REFERENCES users(id),
                redeemed_at TEXT NOT NULL,
                UNIQUE (promo_id, user_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS referral_rewards (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                referrer_user_id BIGINT NOT NULL REFERENCES users(id),
                invited_user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
                order_id BIGINT NOT NULL REFERENCES orders(id),
                reward_days INTEGER NOT NULL,
                created_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS broadcast_campaigns (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                source_chat_id BIGINT NOT NULL,
                source_message_id BIGINT NOT NULL,
                buttons_json TEXT,
                interval_hours INTEGER NOT NULL,
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL,
                last_sent_at TEXT,
                next_run_at TEXT NOT NULL,
                last_success_count INTEGER NOT NULL DEFAULT 0,
                last_failed_count INTEGER NOT NULL DEFAULT 0
            )
            """,
        )
        for statement in statements:
            await self._execute(statement, conn=conn)

        await self._ensure_column("orders", "payment_provider", "TEXT NOT NULL DEFAULT 'crypto_bot'", conn=conn)
        await self._ensure_column("orders", "payment_invoice_id", "TEXT", conn=conn)
        await self._ensure_column("orders", "payment_label", "TEXT", conn=conn)
        await self._ensure_column("orders", "payment_url", "TEXT", conn=conn)
        await self._ensure_column("orders", "payment_extra_url", "TEXT", conn=conn)
        await self._ensure_column("orders", "payment_status", "TEXT", conn=conn)
        await self._execute(
            """
            UPDATE orders
            SET payment_provider = 'crypto_bot'
            WHERE payment_provider IS NULL OR TRIM(payment_provider) = ''
            """,
            conn=conn,
        )
        await self._execute(
            """
            UPDATE orders
            SET payment_invoice_id = COALESCE(payment_invoice_id, CAST(crypto_invoice_id AS TEXT)),
                payment_label = COALESCE(payment_label, crypto_invoice_hash),
                payment_url = COALESCE(payment_url, crypto_bot_invoice_url),
                payment_extra_url = COALESCE(payment_extra_url, crypto_mini_app_invoice_url),
                payment_status = COALESCE(payment_status, crypto_invoice_status)
            """,
            conn=conn,
        )

    async def _ensure_column(self, table: str, column: str, definition: str, *, conn: Any) -> None:
        row = await self._fetchone(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ? AND column_name = ?
            """,
            (table, column),
            conn=conn,
        )
        if row is not None:
            return
        await self._execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}", conn=conn)

    async def _generate_unique_ref_code(self, *, conn: Any) -> str:
        while True:
            code = secrets.token_urlsafe(6).replace("-", "").replace("_", "").upper()[:10]
            row = await self._fetchone("SELECT 1 FROM users WHERE ref_code = ?", (code,), conn=conn)
            if row is None:
                return code

    async def get_or_create_user(
        self,
        telegram_id: int,
        username: str | None,
        first_name: str | None,
        last_name: str | None,
        referrer_code: str | None = None,
    ) -> dict[str, Any]:
        async with self._connection() as conn:
            existing = await self._fetchone(
                "SELECT * FROM users WHERE telegram_id = ?",
                (telegram_id,),
                conn=conn,
            )
            now_iso = to_iso(utc_now())

            if existing:
                await self._execute(
                    """
                    UPDATE users
                    SET username = ?, first_name = ?, last_name = ?, last_seen_at = ?
                    WHERE telegram_id = ?
                    """,
                    (username, first_name, last_name, now_iso, telegram_id),
                    conn=conn,
                )
                await conn.commit()
                row = await self._fetchone(
                    "SELECT * FROM users WHERE telegram_id = ?",
                    (telegram_id,),
                    conn=conn,
                )
                return row or {}

            referred_by: int | None = None
            if referrer_code:
                referrer = await self._fetchone(
                    "SELECT id, telegram_id FROM users WHERE ref_code = ?",
                    (referrer_code.upper(),),
                    conn=conn,
                )
                if referrer and referrer["telegram_id"] != telegram_id:
                    referred_by = int(referrer["id"])

            ref_code = await self._generate_unique_ref_code(conn=conn)
            created = await self._fetchone(
                """
                INSERT INTO users (
                    telegram_id, username, first_name, last_name, ref_code,
                    referred_by, joined_at, last_seen_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING *
                """,
                (
                    telegram_id,
                    username,
                    first_name,
                    last_name,
                    ref_code,
                    referred_by,
                    now_iso,
                    now_iso,
                ),
                conn=conn,
            )
            await conn.commit()
            return created or {}

    async def get_user_by_telegram_id(self, telegram_id: int) -> dict[str, Any] | None:
        return await self._fetchone("SELECT * FROM users WHERE telegram_id = ?", (telegram_id,))

    async def get_user_by_id(self, user_id: int) -> dict[str, Any] | None:
        return await self._fetchone("SELECT * FROM users WHERE id = ?", (user_id,))

    async def get_settings(self) -> dict[str, str]:
        rows = await self._fetchall("SELECT key, value FROM settings")
        return {str(row["key"]): str(row["value"]) for row in rows}

    async def get_setting(self, key: str) -> str | None:
        row = await self._fetchone("SELECT value FROM settings WHERE key = ?", (key,))
        return str(row["value"]) if row else None

    async def set_setting(self, key: str, value: str) -> None:
        async with self._connection() as conn:
            await self._execute(
                """
                INSERT INTO settings (key, value, updated_at)
                VALUES (?, ?, ?)
                ON CONFLICT(key) DO UPDATE SET
                    value = EXCLUDED.value,
                    updated_at = EXCLUDED.updated_at
                """,
                (key, value, to_iso(utc_now())),
                conn=conn,
            )
            await conn.commit()

    async def set_channel_member(self, telegram_id: int, is_member: bool) -> None:
        async with self._connection() as conn:
            await self._execute(
                "UPDATE users SET is_channel_member = ?, last_seen_at = ? WHERE telegram_id = ?",
                (1 if is_member else 0, to_iso(utc_now()), telegram_id),
                conn=conn,
            )
            await conn.commit()

    async def update_subscription_snapshot(
        self,
        user_id: int,
        remnawave_uuid: str | None,
        short_uuid: str | None,
        subscription_url: str | None,
        expires_at: datetime | None,
    ) -> None:
        async with self._connection() as conn:
            await self._execute(
                """
                UPDATE users
                SET remnawave_uuid = ?, remnawave_short_uuid = ?, remnawave_subscription_url = ?,
                    subscription_expires_at = ?
                WHERE id = ?
                """,
                (
                    remnawave_uuid,
                    short_uuid,
                    subscription_url,
                    to_iso(expires_at),
                    user_id,
                ),
                conn=conn,
            )
            await conn.commit()

    async def create_order(
        self,
        user_id: int,
        plan_key: str,
        plan_name: str,
        days: int,
        base_amount: str,
        final_amount: str,
        currency_type: str,
        fiat: str | None,
        asset: str | None,
        accepted_assets: str | None,
        promo_code: str | None,
        discount_percent: int,
        payment_provider: str,
    ) -> dict[str, Any]:
        async with self._connection() as conn:
            order = await self._fetchone(
                """
                INSERT INTO orders (
                    user_id, plan_key, plan_name, days, base_amount, final_amount,
                    currency_type, fiat, asset, accepted_assets, promo_code, discount_percent,
                    payment_provider, status, created_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?)
                RETURNING *
                """,
                (
                    user_id,
                    plan_key,
                    plan_name,
                    days,
                    base_amount,
                    final_amount,
                    currency_type,
                    fiat,
                    asset,
                    accepted_assets,
                    promo_code,
                    discount_percent,
                    payment_provider,
                    to_iso(utc_now()),
                ),
                conn=conn,
            )
            await conn.commit()
            return order or {}

    async def update_order_invoice(self, order_id: int, invoice: dict[str, Any]) -> None:
        invoice_id = invoice.get("invoice_id")
        invoice_id_text = None if invoice_id in (None, "") else str(invoice_id)
        payment_status = invoice.get("status")
        async with self._connection() as conn:
            await self._execute(
                """
                UPDATE orders
                SET payment_invoice_id = ?, payment_label = ?, payment_url = ?,
                    payment_extra_url = ?, payment_status = ?,
                    crypto_invoice_id = ?, crypto_invoice_hash = ?, crypto_bot_invoice_url = ?,
                    crypto_mini_app_invoice_url = ?, crypto_web_app_invoice_url = ?,
                    crypto_invoice_status = ?, raw_invoice_json = ?
                WHERE id = ?
                """,
                (
                    invoice_id_text,
                    invoice.get("label"),
                    invoice.get("pay_url"),
                    invoice.get("extra_url"),
                    payment_status,
                    int(invoice_id) if str(invoice_id).isdigit() else None,
                    invoice.get("label"),
                    invoice.get("pay_url"),
                    invoice.get("extra_url"),
                    invoice.get("web_app_url"),
                    payment_status,
                    json.dumps(invoice.get("raw") or invoice, ensure_ascii=False),
                    order_id,
                ),
                conn=conn,
            )
            await conn.commit()

    async def mark_order_invoice_status(self, order_id: int, invoice_status: str, raw_invoice: dict[str, Any]) -> None:
        paid_at = raw_invoice.get("paid_at") if invoice_status == "paid" else None
        async with self._connection() as conn:
            await self._execute(
                """
                UPDATE orders
                SET payment_status = ?, crypto_invoice_status = ?, raw_invoice_json = ?,
                    paid_at = COALESCE(paid_at, ?)
                WHERE id = ?
                """,
                (
                    invoice_status,
                    invoice_status,
                    json.dumps(raw_invoice, ensure_ascii=False),
                    paid_at,
                    order_id,
                ),
                conn=conn,
            )
            await conn.commit()

    async def activate_order(self, order_id: int) -> None:
        timestamp = to_iso(utc_now())
        async with self._connection() as conn:
            await self._execute(
                """
                UPDATE orders
                SET status = 'activated', activated_at = ?, paid_at = COALESCE(paid_at, ?)
                WHERE id = ?
                """,
                (timestamp, timestamp, order_id),
                conn=conn,
            )
            await conn.commit()

    async def expire_order(self, order_id: int) -> None:
        async with self._connection() as conn:
            await self._execute("UPDATE orders SET status = 'expired' WHERE id = ?", (order_id,), conn=conn)
            await conn.commit()

    async def get_order(self, order_id: int) -> dict[str, Any] | None:
        return await self._fetchone(
            """
            SELECT o.*, u.telegram_id
            FROM orders o
            JOIN users u ON u.id = o.user_id
            WHERE o.id = ?
            """,
            (order_id,),
        )

    async def get_pending_discount(self, user_id: int) -> int:
        row = await self._fetchone(
            "SELECT pending_discount_percent FROM users WHERE id = ?",
            (user_id,),
        )
        return int(row["pending_discount_percent"]) if row else 0

    async def clear_pending_discount(self, user_id: int) -> None:
        async with self._connection() as conn:
            await self._execute("UPDATE users SET pending_discount_percent = 0 WHERE id = ?", (user_id,), conn=conn)
            await conn.commit()

    async def peek_bonus_days(self, user_id: int) -> int:
        row = await self._fetchone("SELECT bonus_days_balance FROM users WHERE id = ?", (user_id,))
        return int(row["bonus_days_balance"]) if row else 0

    async def consume_bonus_days(self, user_id: int) -> int:
        async with self._connection() as conn:
            row = await self._fetchone(
                "SELECT bonus_days_balance FROM users WHERE id = ?",
                (user_id,),
                conn=conn,
            )
            bonus_days = int(row["bonus_days_balance"]) if row else 0
            if bonus_days <= 0:
                return 0
            await self._execute("UPDATE users SET bonus_days_balance = 0 WHERE id = ?", (user_id,), conn=conn)
            await conn.commit()
            return bonus_days

    async def credit_bonus_days(self, user_id: int, days: int) -> None:
        async with self._connection() as conn:
            await self._execute(
                """
                UPDATE users
                SET bonus_days_balance = bonus_days_balance + ?,
                    total_bonus_days_earned = total_bonus_days_earned + ?
                WHERE id = ?
                """,
                (days, days, user_id),
                conn=conn,
            )
            await conn.commit()

    async def restore_bonus_balance(self, user_id: int, days: int) -> None:
        async with self._connection() as conn:
            await self._execute(
                "UPDATE users SET bonus_days_balance = bonus_days_balance + ? WHERE id = ?",
                (days, user_id),
                conn=conn,
            )
            await conn.commit()

    async def get_profile_stats(self, user_id: int) -> dict[str, Any]:
        user = await self.get_user_by_id(user_id)
        if not user:
            return {}

        referral_count_row = await self._fetchone(
            "SELECT COUNT(*) AS count FROM users WHERE referred_by = ?",
            (user_id,),
        )
        paid_referral_row = await self._fetchone(
            "SELECT COUNT(*) AS count FROM referral_rewards WHERE referrer_user_id = ?",
            (user_id,),
        )
        orders_row = await self._fetchone(
            "SELECT COUNT(*) AS count FROM orders WHERE user_id = ? AND status = 'activated'",
            (user_id,),
        )
        total_orders_row = await self._fetchone(
            "SELECT COUNT(*) AS count FROM orders WHERE user_id = ?",
            (user_id,),
        )
        spent_total_row = await self._fetchone(
            """
            SELECT COALESCE(SUM(CAST(final_amount AS REAL)), 0) AS total
            FROM orders
            WHERE user_id = ? AND status = 'activated'
            """,
            (user_id,),
        )

        return {
            "user": user,
            "referrals_total": int(referral_count_row["count"]) if referral_count_row else 0,
            "paid_referrals": int(paid_referral_row["count"]) if paid_referral_row else 0,
            "paid_orders": int(orders_row["count"]) if orders_row else 0,
            "orders_total": int(total_orders_row["count"]) if total_orders_row else 0,
            "spent_total": float(spent_total_row["total"]) if spent_total_row else 0.0,
        }

    async def set_pending_discount(self, user_id: int, discount_percent: int) -> None:
        async with self._connection() as conn:
            await self._execute(
                "UPDATE users SET pending_discount_percent = ? WHERE id = ?",
                (discount_percent, user_id),
                conn=conn,
            )
            await conn.commit()

    async def search_users(self, query: str, limit: int = 10) -> list[dict[str, Any]]:
        normalized = query.strip()
        if not normalized:
            return []

        if normalized.isdigit():
            value = int(normalized)
            rows = await self._fetchall(
                """
                SELECT *
                FROM users
                WHERE telegram_id = ? OR id = ?
                ORDER BY id DESC
                LIMIT ?
                """,
                (value, value, limit),
            )
        else:
            username_query = normalized.lstrip("@").lower()
            like_query = f"%{username_query}%"
            name_like_query = f"%{normalized.lower()}%"
            rows = await self._fetchall(
                """
                SELECT *
                FROM users
                WHERE UPPER(ref_code) = ?
                   OR LOWER(COALESCE(username, '')) = ?
                   OR LOWER(COALESCE(username, '')) LIKE ?
                   OR LOWER(COALESCE(first_name, '')) LIKE ?
                   OR LOWER(COALESCE(last_name, '')) LIKE ?
                ORDER BY last_seen_at DESC, id DESC
                LIMIT ?
                """,
                (
                    normalized.upper(),
                    username_query,
                    like_query,
                    name_like_query,
                    name_like_query,
                    limit,
                ),
            )

        return rows

    async def list_recent_users(self, limit: int = 10) -> list[dict[str, Any]]:
        return await self._fetchall(
            """
            SELECT *
            FROM users
            ORDER BY joined_at DESC, id DESC
            LIMIT ?
            """,
            (limit,),
        )

    async def list_user_orders(self, user_id: int, limit: int = 10) -> list[dict[str, Any]]:
        return await self._fetchall(
            """
            SELECT o.*, u.telegram_id
            FROM orders o
            JOIN users u ON u.id = o.user_id
            WHERE o.user_id = ?
            ORDER BY o.id DESC
            LIMIT ?
            """,
            (user_id, limit),
        )

    async def get_user_admin_profile(self, user_id: int) -> dict[str, Any]:
        profile_stats = await self.get_profile_stats(user_id)
        if not profile_stats:
            return {}

        recent_orders = await self.list_user_orders(user_id, limit=5)
        return {
            **profile_stats,
            "recent_orders": recent_orders,
        }

    async def get_admin_dashboard(self) -> dict[str, Any]:
        now = utc_now()
        now_iso = to_iso(now)
        day_ago_iso = to_iso(now - timedelta(days=1))
        week_ago_iso = to_iso(now - timedelta(days=7))

        total_users_row = await self._fetchone("SELECT COUNT(*) AS count FROM users")
        users_24h_row = await self._fetchone(
            "SELECT COUNT(*) AS count FROM users WHERE joined_at >= ?",
            (day_ago_iso,),
        )
        users_7d_row = await self._fetchone(
            "SELECT COUNT(*) AS count FROM users WHERE joined_at >= ?",
            (week_ago_iso,),
        )
        active_subscriptions_row = await self._fetchone(
            """
            SELECT COUNT(*) AS count
            FROM users
            WHERE subscription_expires_at IS NOT NULL AND subscription_expires_at > ?
            """,
            (now_iso,),
        )
        expired_subscriptions_row = await self._fetchone(
            """
            SELECT COUNT(*) AS count
            FROM users
            WHERE subscription_expires_at IS NOT NULL AND subscription_expires_at <= ?
            """,
            (now_iso,),
        )
        total_orders_row = await self._fetchone("SELECT COUNT(*) AS count FROM orders")
        pending_orders_row = await self._fetchone("SELECT COUNT(*) AS count FROM orders WHERE status = 'pending'")
        activated_orders_row = await self._fetchone("SELECT COUNT(*) AS count FROM orders WHERE status = 'activated'")
        paid_not_activated_row = await self._fetchone(
            """
            SELECT COUNT(*) AS count
            FROM orders
            WHERE payment_status = 'paid' AND status != 'activated'
            """
        )
        revenue_row = await self._fetchone(
            """
            SELECT COALESCE(SUM(CAST(final_amount AS REAL)), 0) AS total
            FROM orders
            WHERE status = 'activated'
            """
        )
        active_promos_row = await self._fetchone("SELECT COUNT(*) AS count FROM promo_codes WHERE is_active = 1")
        promo_redemptions_row = await self._fetchone("SELECT COUNT(*) AS count FROM promo_redemptions")
        referral_days_row = await self._fetchone(
            "SELECT COALESCE(SUM(reward_days), 0) AS total FROM referral_rewards"
        )

        return {
            "total_users": int(total_users_row["count"]) if total_users_row else 0,
            "users_24h": int(users_24h_row["count"]) if users_24h_row else 0,
            "users_7d": int(users_7d_row["count"]) if users_7d_row else 0,
            "active_subscriptions": int(active_subscriptions_row["count"]) if active_subscriptions_row else 0,
            "expired_subscriptions": int(expired_subscriptions_row["count"]) if expired_subscriptions_row else 0,
            "total_orders": int(total_orders_row["count"]) if total_orders_row else 0,
            "pending_orders": int(pending_orders_row["count"]) if pending_orders_row else 0,
            "activated_orders": int(activated_orders_row["count"]) if activated_orders_row else 0,
            "paid_not_activated": int(paid_not_activated_row["count"]) if paid_not_activated_row else 0,
            "total_revenue": float(revenue_row["total"]) if revenue_row else 0.0,
            "active_promos": int(active_promos_row["count"]) if active_promos_row else 0,
            "promo_redemptions": int(promo_redemptions_row["count"]) if promo_redemptions_row else 0,
            "referral_reward_days": int(referral_days_row["total"]) if referral_days_row else 0,
            "recent_orders": await self.list_recent_orders(limit=5),
        }

    async def list_recent_orders(self, limit: int = 10) -> list[dict[str, Any]]:
        return await self._fetchall(
            """
            SELECT o.*, u.telegram_id
            FROM orders o
            JOIN users u ON u.id = o.user_id
            ORDER BY o.id DESC
            LIMIT ?
            """,
            (limit,),
        )

    async def search_orders(self, query: str, limit: int = 10) -> list[dict[str, Any]]:
        normalized = query.strip()
        if not normalized:
            return []

        if normalized.isdigit():
            value = int(normalized)
            rows = await self._fetchall(
                """
                SELECT o.*, u.telegram_id
                FROM orders o
                JOIN users u ON u.id = o.user_id
                WHERE o.id = ? OR u.telegram_id = ?
                ORDER BY o.id DESC
                LIMIT ?
                """,
                (value, value, limit),
            )
        else:
            like_query = f"%{normalized.lower()}%"
            rows = await self._fetchall(
                """
                SELECT o.*, u.telegram_id
                FROM orders o
                JOIN users u ON u.id = o.user_id
                WHERE LOWER(o.plan_name) LIKE ?
                   OR LOWER(o.plan_key) LIKE ?
                   OR LOWER(COALESCE(o.promo_code, '')) LIKE ?
                   OR LOWER(o.status) LIKE ?
                ORDER BY o.id DESC
                LIMIT ?
                """,
                (like_query, like_query, like_query, like_query, limit),
            )

        return rows

    async def list_promos(self, limit: int = 10, *, active_only: bool = False) -> list[dict[str, Any]]:
        where_clause = "WHERE p.is_active = 1" if active_only else ""
        return await self._fetchall(
            f"""
            SELECT p.*, COUNT(r.id) AS redemptions_count
            FROM promo_codes p
            LEFT JOIN promo_redemptions r ON r.promo_id = p.id
            {where_clause}
            GROUP BY p.id
            ORDER BY p.created_at DESC, p.id DESC
            LIMIT ?
            """,
            (limit,),
        )

    async def get_promo(self, promo_id: int) -> dict[str, Any] | None:
        return await self._fetchone(
            """
            SELECT p.*, COUNT(r.id) AS redemptions_count
            FROM promo_codes p
            LEFT JOIN promo_redemptions r ON r.promo_id = p.id
            WHERE p.id = ?
            GROUP BY p.id
            """,
            (promo_id,),
        )

    async def list_user_telegram_ids(self) -> list[int]:
        rows = await self._fetchall("SELECT telegram_id FROM users ORDER BY id ASC")
        return [int(row["telegram_id"]) for row in rows]

    async def list_broadcast_campaigns(self, limit: int = 20) -> list[dict[str, Any]]:
        return await self._fetchall(
            """
            SELECT *
            FROM broadcast_campaigns
            ORDER BY id DESC
            LIMIT ?
            """,
            (limit,),
        )

    async def get_broadcast_campaign(self, campaign_id: int) -> dict[str, Any] | None:
        return await self._fetchone(
            "SELECT * FROM broadcast_campaigns WHERE id = ?",
            (campaign_id,),
        )

    async def create_broadcast_campaign(
        self,
        *,
        name: str,
        source_chat_id: int,
        source_message_id: int,
        buttons_json: str | None,
        interval_hours: int,
    ) -> dict[str, Any]:
        async with self._connection() as conn:
            now = utc_now()
            next_run_at = now + timedelta(hours=interval_hours)
            campaign = await self._fetchone(
                """
                INSERT INTO broadcast_campaigns (
                    name, source_chat_id, source_message_id, buttons_json, interval_hours,
                    created_at, next_run_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                RETURNING *
                """,
                (
                    name,
                    source_chat_id,
                    source_message_id,
                    buttons_json,
                    interval_hours,
                    to_iso(now),
                    to_iso(next_run_at),
                ),
                conn=conn,
            )
            await conn.commit()
            return campaign or {}

    async def set_broadcast_campaign_active(self, campaign_id: int, is_active: bool) -> None:
        async with self._connection() as conn:
            campaign = await self._fetchone(
                "SELECT * FROM broadcast_campaigns WHERE id = ?",
                (campaign_id,),
                conn=conn,
            )
            if not campaign:
                return
            now = utc_now()
            next_run_at = now + timedelta(hours=int(campaign["interval_hours"]))
            await self._execute(
                """
                UPDATE broadcast_campaigns
                SET is_active = ?, next_run_at = ?
                WHERE id = ?
                """,
                (
                    1 if is_active else 0,
                    to_iso(next_run_at if is_active else from_iso(campaign["next_run_at"]) or now),
                    campaign_id,
                ),
                conn=conn,
            )
            await conn.commit()

    async def schedule_broadcast_campaign_now(self, campaign_id: int) -> None:
        async with self._connection() as conn:
            await self._execute(
                "UPDATE broadcast_campaigns SET next_run_at = ? WHERE id = ?",
                (to_iso(utc_now()), campaign_id),
                conn=conn,
            )
            await conn.commit()

    async def list_due_broadcast_campaigns(self, now: datetime | None = None) -> list[dict[str, Any]]:
        current = to_iso(now or utc_now())
        return await self._fetchall(
            """
            SELECT *
            FROM broadcast_campaigns
            WHERE is_active = 1 AND next_run_at <= ?
            ORDER BY next_run_at ASC, id ASC
            """,
            (current,),
        )

    async def mark_broadcast_campaign_sent(
        self,
        campaign_id: int,
        *,
        success_count: int,
        failed_count: int,
    ) -> None:
        async with self._connection() as conn:
            campaign = await self._fetchone(
                "SELECT * FROM broadcast_campaigns WHERE id = ?",
                (campaign_id,),
                conn=conn,
            )
            if not campaign:
                return
            now = utc_now()
            next_run_at = now + timedelta(hours=int(campaign["interval_hours"]))
            await self._execute(
                """
                UPDATE broadcast_campaigns
                SET last_sent_at = ?, next_run_at = ?, last_success_count = ?, last_failed_count = ?
                WHERE id = ?
                """,
                (
                    to_iso(now),
                    to_iso(next_run_at),
                    success_count,
                    failed_count,
                    campaign_id,
                ),
                conn=conn,
            )
            await conn.commit()

    async def create_promo(
        self,
        code: str,
        bonus_days: int,
        discount_percent: int,
        max_uses: int,
        description: str | None,
    ) -> None:
        async with self._connection() as conn:
            await self._execute(
                """
                INSERT INTO promo_codes (
                    code, bonus_days, discount_percent, max_uses, description, created_at
                )
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(code) DO UPDATE SET
                    bonus_days = EXCLUDED.bonus_days,
                    discount_percent = EXCLUDED.discount_percent,
                    max_uses = EXCLUDED.max_uses,
                    description = EXCLUDED.description,
                    is_active = 1
                """,
                (
                    code.upper(),
                    bonus_days,
                    discount_percent,
                    max_uses,
                    description,
                    to_iso(utc_now()),
                ),
                conn=conn,
            )
            await conn.commit()

    async def disable_promo(self, code: str) -> bool:
        async with self._connection() as conn:
            cursor = await self._execute(
                "UPDATE promo_codes SET is_active = 0 WHERE code = ?",
                (code.upper(),),
                conn=conn,
            )
            await conn.commit()
            return cursor.rowcount > 0

    async def apply_promo_code(self, user_id: int, code: str) -> dict[str, Any]:
        async with self._connection() as conn:
            promo = await self._fetchone("SELECT * FROM promo_codes WHERE code = ?", (code.upper(),), conn=conn)
            if promo is None:
                raise ValueError("Такого промокода нет.")
            if int(promo["is_active"]) != 1:
                raise ValueError("Промокод выключен.")
            if promo["expires_at"] and from_iso(promo["expires_at"]) < utc_now():
                raise ValueError("Срок действия промокода закончился.")
            if int(promo["max_uses"]) > 0 and int(promo["uses_count"]) >= int(promo["max_uses"]):
                raise ValueError("Лимит активаций у промокода исчерпан.")

            exists = await self._fetchone(
                "SELECT 1 FROM promo_redemptions WHERE promo_id = ? AND user_id = ?",
                (promo["id"], user_id),
                conn=conn,
            )
            if exists is not None:
                raise ValueError("Этот промокод уже активирован.")

            await self._execute(
                "INSERT INTO promo_redemptions (promo_id, user_id, redeemed_at) VALUES (?, ?, ?)",
                (promo["id"], user_id, to_iso(utc_now())),
                conn=conn,
            )
            await self._execute(
                "UPDATE promo_codes SET uses_count = uses_count + 1 WHERE id = ?",
                (promo["id"],),
                conn=conn,
            )

            bonus_days = int(promo["bonus_days"])
            discount_percent = int(promo["discount_percent"])
            if bonus_days > 0:
                await self._execute(
                    """
                    UPDATE users
                    SET bonus_days_balance = bonus_days_balance + ?,
                        total_bonus_days_earned = total_bonus_days_earned + ?
                    WHERE id = ?
                    """,
                    (bonus_days, bonus_days, user_id),
                    conn=conn,
                )
            if discount_percent > 0:
                await self._execute(
                    """
                    UPDATE users
                    SET pending_discount_percent = CASE
                        WHEN pending_discount_percent < ? THEN ?
                        ELSE pending_discount_percent
                    END
                    WHERE id = ?
                    """,
                    (discount_percent, discount_percent, user_id),
                    conn=conn,
                )
            await conn.commit()
            return promo

    async def register_referral_reward(self, invited_user_id: int, order_id: int, reward_days: int) -> int | None:
        async with self._connection() as conn:
            invited = await self._fetchone("SELECT * FROM users WHERE id = ?", (invited_user_id,), conn=conn)
            if not invited or invited["referred_by"] is None:
                return None

            exists = await self._fetchone(
                "SELECT 1 FROM referral_rewards WHERE invited_user_id = ?",
                (invited_user_id,),
                conn=conn,
            )
            if exists is not None:
                return None

            referrer_id = int(invited["referred_by"])
            await self._execute(
                """
                INSERT INTO referral_rewards (
                    referrer_user_id, invited_user_id, order_id, reward_days, created_at
                )
                VALUES (?, ?, ?, ?, ?)
                """,
                (referrer_id, invited_user_id, order_id, reward_days, to_iso(utc_now())),
                conn=conn,
            )
            await self._execute(
                """
                UPDATE users
                SET bonus_days_balance = bonus_days_balance + ?,
                    total_bonus_days_earned = total_bonus_days_earned + ?
                WHERE id = ?
                """,
                (reward_days, reward_days, referrer_id),
                conn=conn,
            )
            await conn.commit()
            return referrer_id

    async def recent_promos(self) -> list[dict[str, Any]]:
        return await self._fetchall(
            """
            SELECT code, bonus_days, discount_percent, description
            FROM promo_codes
            WHERE is_active = 1
            ORDER BY created_at DESC
            LIMIT 5
            """
        )
